### ISSUE TITLE
some questions about dataset 

### ISSUE THREAD

**Issue by yzz-cver** [duanzhiihao/CEPDOF_tools#2]
Hello, I want to ask what software is used to annotate the CEPDOF dataset ？How to determine the sign of the angle ？Looking forward to your reply！

**Comment by duanzhiihao** [comment]
Hi, we used an internal version of https://github.com/tzutalin/labelImg, modified to support rotated bounding boxes. Our version is not publicly available, but there are other public tools like https://github.com/cgvict/roLabelImg.

Regarding the sign of angle, we use the following convention:
- width<= height
- the angle is within -90 to +90 degrees, clockwise.

Under these constraints, any bounding box can be uniquely described by a group of [center x, center y, width, height, angle].

**Comment by yzz-cver** [comment]
Ok, thank you!
