### ISSUE TITLE
question about rotation matrix

### ISSUE THREAD

**Issue by yzz-cver** [duanzhiihao/CEPDOF_tools#3]
Hello, according to the definition of the angle of the dataset, why is the rotation matrix in the following representation.
![image](https://user-images.githubusercontent.com/53545589/165212855-277b38ee-fb19-4fb1-ab66-6f86b5a26ffc.png)
![image](https://user-images.githubusercontent.com/53545589/165212947-78855e8e-7ff3-45bb-a05c-f6a5d69dfa56.png)
Why not this representation？R = np.asarray([[c, -s], [s, c]])，thank you!

**Comment by duanzhiihao** [comment]
Hi, thank you for your interest.

If I understand your question correctly, you are referring to this line in the code:
https://github.com/duanzhiihao/CEPDOF_tools/blob/20f3babe275b0ca10ebff25a0f62be8d521795c9/cepdof_api.py#L225

You said:
> Why not this representation？R = np.asarray([[c, -s], [s, c]])，thank you!

Your version corresponds to a **counterclockwise** rotation matrix. See for example Wikipedia:
![image](https://user-images.githubusercontent.com/24869582/165219714-471654a1-97f1-438d-8cba-da82ca67548d.png)

However, in our case, the degree is **clockwise**, as you highlighted in your screenshot. So we should replace `theta` with `-theta` in the matrix, which will result in our version as in our code.

**Comment by yzz-cver** [comment]
The figure below is the calculated rotation matrix. I don't know which step is wrong. Please help me to take a look. Thank you.
![b5fffc0b28cc10d665ee523f5c6b7a3](https://user-images.githubusercontent.com/53545589/165227241-aec7b555-7797-4a09-a2e3-72795057bb3d.jpg)

**Comment by duanzhiihao** [comment]
Your definition of `alpha` is different than in our case. In our case,  `alpha` should be the **clock-wise rotation angle from the vertical axis pointing up**. See the image below.
![image](https://user-images.githubusercontent.com/24869582/165335879-6e1df882-0230-4f4e-83b8-6f3c452642be.png)

With the above definition, your calculation would be correct.

Please let me know if this helps or not.

**Comment by yzz-cver** [comment]
Thank you for your patience to explain, it helped me a lot！

**Comment by duanzhiihao** [comment]
No problem :) I'm happy that you figured it out!

**Comment by yzz-cver** [comment]
Sorry, there is one place that I still don't fully understand. The solution of the rotation matrix is shown in the figure, and the obtained matrix is still incorrect.
![0677122b5c663f8e918b924939de2a1](https://user-images.githubusercontent.com/53545589/165474807-09a09932-fa8e-41cd-8907-d4e2bbdbf83a.jpg)

**Comment by duanzhiihao** [comment]
Your calculation in your setting is indeed correct. But I just recall that we need to reverse the y axis (should be pointing down), since in the image coordinate, the top-left corner is the origin (0,0). I also did it wrong in my previous reply. See below for the correct version.

![image](https://user-images.githubusercontent.com/24869582/165560299-f0a7c649-fbca-4f0d-8823-d1cbc917072d.png)

**Comment by yzz-cver** [comment]
I understand, thank you very much！
